Create CelebrityProblem.cpp
ravi-mohans/hacktoberfestdsa pull request #5
Opened 2022-10-10 09:18 UTC by ProgrammerDG

2022-10-10 14:11 UTC, ravi-mohans requested changes
add the problem statement in code in the form of comment .

2022-10-10 17:27 UTC, ProgrammerDG commented
Ok

On Mon, 10 Oct 2022, 7:41 pm ravi-mohans, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> add the problem statement in code in the form of comment .
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ravi-mohans/hacktoberfestdsa/pull/5#pullrequestreview-1136089960>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARG7FW4HMVI7TYFS62HT42LWCQPX7ANCNFSM6AAAAAARBE5ULY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-10 17:40 UTC, ProgrammerDG commented
Added

On Mon, 10 Oct 2022, 10:57 pm Deepanshu Goyal, ***@***.***>
wrote:

> Ok
>
> On Mon, 10 Oct 2022, 7:41 pm ravi-mohans, ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> add the problem statement in code in the form of comment .
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ravi-mohans/hacktoberfestdsa/pull/5#pullrequestreview-1136089960>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARG7FW4HMVI7TYFS62HT42LWCQPX7ANCNFSM6AAAAAARBE5ULY>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-10-11 16:55 UTC, ravi-mohans approved these changes
hacktoberfest-accepted

2022-10-11 16:56 UTC, merged